--
-- PostgreSQL database dump
--

\restrict GBXDQp5rbc7RIsq8MWBPX1e4PSlQf7wIW7hBYkmdUE840SFOYqTt3FoWCoP7bEU

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;

SET lock_timeout = 0;

SET idle_in_transaction_session_timeout = 0;

SET transaction_timeout = 0;

SET client_encoding = 'UTF8';

SET standard_conforming_strings = on;

SELECT pg_catalog.set_config ('search_path', '', false);

SET check_function_bodies = false;

SET xmloption = content;

SET client_min_messages = warning;

SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;

ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: answers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.answers (
    answer_id integer NOT NULL,
    question_id integer,
    answer_text character varying,
    answer_level integer,
    answer_weight double precision
);

ALTER TABLE public.answers OWNER TO postgres;

--
-- Name: cluster_profiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cluster_profiles (
    cluster_id bigint NOT NULL,
    cluster_name character varying,
    score_min real,
    score_max real
);

ALTER TABLE public.cluster_profiles OWNER TO postgres;

--
-- Name: cluster_profiles_cluster_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cluster_profiles
ALTER COLUMN cluster_id
ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cluster_profiles_cluster_id_seq START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

--
-- Name: companies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.companies (
    company_id integer NOT NULL,
    industry character varying,
    website character varying,
    number_of_employees character varying,
    city character varying,
    company_name character varying,
    email text
);

ALTER TABLE public.companies OWNER TO postgres;

--
-- Name: dimensions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dimensions (
    dimension_id integer NOT NULL,
    dimension_name character varying,
    dimension_weight double precision
);

ALTER TABLE public.dimensions OWNER TO postgres;

--
-- Name: questions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.questions (
    question_id integer NOT NULL,
    dimension_id integer,
    header character varying,
    question_text character varying,
    type character varying,
    weight double precision,
    optional boolean
);

ALTER TABLE public.questions OWNER TO postgres;

--
-- Name: response_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.response_items (
    item_id integer NOT NULL,
    response_id integer,
    question_id integer,
    answers integer[]
);

ALTER TABLE public.response_items OWNER TO postgres;

--
-- Name: responses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.responses (
    response_id integer NOT NULL,
    company_id integer,
    total_score character varying,
    created_at timestamp with time zone,
    cluster_id bigint
);

ALTER TABLE public.responses OWNER TO postgres;

--
-- Name: answers answers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.answers
ADD CONSTRAINT answers_pkey PRIMARY KEY (answer_id);

--
-- Name: cluster_profiles cluster_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cluster_profiles
ADD CONSTRAINT cluster_profiles_pkey PRIMARY KEY (cluster_id);

--
-- Name: companies companies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.companies
ADD CONSTRAINT companies_pkey PRIMARY KEY (company_id);

--
-- Name: dimensions dimensions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dimensions
ADD CONSTRAINT dimensions_pkey PRIMARY KEY (dimension_id);

--
-- Name: questions questions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions
ADD CONSTRAINT questions_pkey PRIMARY KEY (question_id);

--
-- Name: response_items response_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.response_items
ADD CONSTRAINT response_items_pkey PRIMARY KEY (item_id);

--
-- Name: responses responses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.responses
ADD CONSTRAINT responses_pkey PRIMARY KEY (response_id);

--
-- Name: answers answers_question_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.answers
ADD CONSTRAINT answers_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.questions (question_id);

--
-- Name: questions questions_dimension_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.questions
ADD CONSTRAINT questions_dimension_id_fkey FOREIGN KEY (dimension_id) REFERENCES public.dimensions (dimension_id);

--
-- Name: response_items response_items_question_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.response_items
ADD CONSTRAINT response_items_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.questions (question_id);

--
-- Name: response_items response_items_response_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.response_items
ADD CONSTRAINT response_items_response_id_fkey FOREIGN KEY (response_id) REFERENCES public.responses (response_id);

--
-- Name: responses responses_cluster_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.responses
ADD CONSTRAINT responses_cluster_id_fkey FOREIGN KEY (cluster_id) REFERENCES public.cluster_profiles (cluster_id);

--
-- Name: responses responses_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.responses
ADD CONSTRAINT responses_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies (company_id);

--
-- Name: cluster_profiles; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.cluster_profiles ENABLE ROW LEVEL SECURITY;

--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA public TO postgres;

GRANT USAGE ON SCHEMA public TO anon;

GRANT USAGE ON SCHEMA public TO authenticated;

GRANT USAGE ON SCHEMA public TO service_role;

--
-- Name: TABLE answers; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.answers TO anon;

GRANT ALL ON TABLE public.answers TO authenticated;

GRANT ALL ON TABLE public.answers TO service_role;

--
-- Name: TABLE cluster_profiles; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.cluster_profiles TO anon;

GRANT ALL ON TABLE public.cluster_profiles TO authenticated;

GRANT ALL ON TABLE public.cluster_profiles TO service_role;

--
-- Name: SEQUENCE cluster_profiles_cluster_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.cluster_profiles_cluster_id_seq TO anon;

GRANT ALL ON SEQUENCE public.cluster_profiles_cluster_id_seq TO authenticated;

GRANT ALL ON SEQUENCE public.cluster_profiles_cluster_id_seq TO service_role;

--
-- Name: TABLE companies; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.companies TO anon;

GRANT ALL ON TABLE public.companies TO authenticated;

GRANT ALL ON TABLE public.companies TO service_role;

--
-- Name: TABLE dimensions; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.dimensions TO anon;

GRANT ALL ON TABLE public.dimensions TO authenticated;

GRANT ALL ON TABLE public.dimensions TO service_role;

--
-- Name: TABLE questions; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.questions TO anon;

GRANT ALL ON TABLE public.questions TO authenticated;

GRANT ALL ON TABLE public.questions TO service_role;

--
-- Name: TABLE response_items; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.response_items TO anon;

GRANT ALL ON TABLE public.response_items TO authenticated;

GRANT ALL ON TABLE public.response_items TO service_role;

--
-- Name: TABLE responses; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.responses TO anon;

GRANT ALL ON TABLE public.responses TO authenticated;

GRANT ALL ON TABLE public.responses TO service_role;

--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
GRANT ALL ON SEQUENCES TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
GRANT ALL ON SEQUENCES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
GRANT ALL ON SEQUENCES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
GRANT ALL ON SEQUENCES TO service_role;

--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public
GRANT ALL ON SEQUENCES TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public
GRANT ALL ON SEQUENCES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public
GRANT ALL ON SEQUENCES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public
GRANT ALL ON SEQUENCES TO service_role;

--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
GRANT ALL ON FUNCTIONS TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
GRANT ALL ON FUNCTIONS TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
GRANT ALL ON FUNCTIONS TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
GRANT ALL ON FUNCTIONS TO service_role;

--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public
GRANT ALL ON FUNCTIONS TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public
GRANT ALL ON FUNCTIONS TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public
GRANT ALL ON FUNCTIONS TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public
GRANT ALL ON FUNCTIONS TO service_role;

--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
GRANT ALL ON TABLES TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
GRANT ALL ON TABLES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
GRANT ALL ON TABLES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
GRANT ALL ON TABLES TO service_role;

--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public
GRANT ALL ON TABLES TO postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public
GRANT ALL ON TABLES TO anon;

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public
GRANT ALL ON TABLES TO authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public
GRANT ALL ON TABLES TO service_role;

--
-- PostgreSQL database dump complete
--

\unrestrict GBXDQp5rbc7RIsq8MWBPX1e4PSlQf7wIW7hBYkmdUE840SFOYqTt3FoWCoP7bEU